apiVersion: v1
kind: Template
metadata:
  name: rsvp-template
  annotations:
    description: "RSVP application"
    tags: "rsvp"
objects:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: rsvp
  spec:
    template:
      metadata:
        labels:
          app: rsvp
      spec:
        containers:
         - name: rsvp-app
           image: teamcloudyuga/rsvpapp
           imagePullPolicy: IfNotPresent 
           livenessProbe:
             httpGet:
               path: /
               port: 5000
             periodSeconds: 30
             timeoutSeconds: 1
             initialDelaySeconds: 50
           env:
           - name: MONGODB_HOST
             value: mongodb
           ports:
           - containerPort: 5000
             name: web-port

- apiVersion: v1
  kind: Service
  metadata:
    name: rsvp
    labels:
      app: rsvp
  spec:
    type: NodePort
    ports:
    - port: 80
      targetPort: web-port
      protocol: TCP
    selector:
      app: rsvp
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: rsvp-db
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          appdb: rsvpdb
      spec:
        containers:
        - name: rsvpd-db
          image: mongo:3.3
          env:
          - name: MONGODB_DATABASE
            value: rsvpdata
          ports:
          - containerPort: 27017
- apiVersion: v1
  kind: Service
  metadata:
    name: mongodb
    labels:
      app: rsvpdb
  spec:
    ports:
    - port: 27017
      protocol: TCP
    selector:
      appdb: rsvpdb
